# /home/mel-houd/goinfre/test
volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/mel-houd/goinfre/test/mariadb
      o: bind

  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/mel-houd/goinfre/test/wordpress
      o: bind

networks:
  inception:
    name: inception
    driver: bridge

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: dockerfile
    image: nginx
    ports:
      - "9999:443"
    volumes:
      - wordpress-volume:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception

  mariadb:
    env_file:
      - .env
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - inception


  wordpress:
    env_file:
      - .env
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    volumes:
      - wordpress-volume:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception

