volumes:
  mariadb-volume:
    name: "mariadb-volume"

  wordpress-volume:
    name: "wordpress-volume"

networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: dockerfile
    image: nginx
    ports:
      - "8888:443"
    volumes:
      - wordpress-volume:/var/www/html
    depends_on:
      - wordpress
 

  mariadb:
    env_file:
      - .env
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    ports:
      - 3333:3306
    volumes:
      - mariadb-volume:/var/lib/mysql
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  wordpress:
    env_file:
      - .env
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    ports:
      - 9999:9000
    volumes:
      - wordpress-volume:/var/www/html
    depends_on:
      - mariadb

