version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: dockerfile
    image: nginx
    ports:
      - "8888:443"
    volumes:
      - wordpress-volume:/srcs/files

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    ports:
      - 3333:3306
    volumes:
      - mariadb-volume:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    ports:
      - 9999:9000
    volumes:
      - wordpress-volume:/srcs/wp-files


volumes:
  mariadb-volume:
    # name:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mel-houd/data/db-volume
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mel-houd/data/wordpress-volume