FROM debian:bullseye

RUN apt-get update && apt-get install -y \
    mariadb-server \
    netcat \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /run/mysqld \
    && chown -R mysql:mysql /run/mysqld \
    && chown -R mysql:mysql /var/lib/mysql

WORKDIR /srcs

COPY ./tools/init.sh /srcs/

RUN chmod +x /srcs/init.sh

# CMD [ "tail", "-f", "/dev/null" ]

CMD [ "bash", "-c", "/srcs/init.sh" ]
