FROM debian:bullseye

RUN apt-get update && apt-get install -y \
    mariadb-server

COPY ./tools/my.cnf /etc/mysql/mariadb.conf.d/my.cnf

COPY ./tools/init.sh /init.sh

RUN chmod +x /init.sh

CMD [ "/init.sh" ]