FROM debian:bullseye

RUN apt-get install -y \
    curl \
    php \
    php-fpm \
    php-mysql \
    mariadb-client \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
    
RUN curl -sSLo /usr/share/keyrings/debsuryorg-archive-keyring.gpg https://packages.sury.org/php/apt.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/debsuryorg-archive-keyring.gpg] https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list

RUN mkdir -p /var/www/html/ && \
    chown -R www-data:www-data /var/www/html

RUN mkdir -p /run/php/ && chown -R www-data:www-data /run/php/

WORKDIR /var/www/html

RUN sed -i "s|^listen = .*|listen = 0.0.0.0:9000|" /etc/php/7.4/fpm/pool.d/www.conf

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/wp

COPY ./tools/init.sh /init.sh

RUN chmod +x /init.sh

CMD [ "/init.sh" ]