FROM debian:bullseye

RUN apt-get update && apt-get install -y \
    nginx \
    netcat \
    openssl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /var/www/html

RUN mkdir /keys

# gen private key
RUN openssl genpkey -algorithm RSA -out /keys/private.key

# gen CSR with subject information
RUN openssl req -new -key /keys/private.key -out /keys/cert.csr \
-subj "/C=/ST=/L=City/O=/OU=/CN="

# gen self-signed certificate
RUN openssl x509 -req -days 365 \
-in /keys/cert.csr \
-signkey /keys/private.key \
-out /keys/cert.crt

COPY ./tools/server.conf /etc/nginx/conf.d/server.conf

COPY ./tools/init.sh /keys
RUN chmod +x /keys/init.sh

#CMD [ "tail", "-f", "/dev/null" ]
CMD [ "bash", "-c", "/keys/init.sh;" ]