FROM debian:bullseye

RUN apt-get update && apt-get install -y \
    nginx \
    iputils-ping \
    openssl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /srcs

RUN mkdir keys files

# gen private key
RUN openssl genpkey -algorithm RSA -out /srcs/keys/private.key

# gen CSR with subject information
RUN openssl req -new -key /srcs/keys/private.key -out /srcs/keys/cert.csr \
-subj "/C=/ST=/L=City/O=/OU=/CN="

# gen self-signed certificate
RUN openssl x509 -req -days 365 \
-in /srcs/keys/cert.csr \
-signkey /srcs/keys/private.key \
-out /srcs/keys/cert.crt

COPY ./tools/server.conf /etc/nginx/conf.d/my.conf

EXPOSE 443
    
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]